# Site settings
title: Fixecl的个人博客
email: fixecl@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  欢迎访问
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fixecl.github.io" # the base hostname & protocol for your site
twitter_username: ff
github_username:  fixecl

# Build settings
markdown: kramdown

paginate: 4

author: Fixecl

gems: [jekyll-paginate]
